### PR TITLE
Add TypeScript Declarations

### PR DESCRIPTION
**Pull request by lmmarsano**
This project is highly useful.
I would love to use it with TypeScript.
This branch provides TypeScript declarations by rewriting in TypeScript and building to Javascript to produce the declarations.
Please let me know if this can get accepted or if it needs anything.
Thanks.

### CODE REVIEW

**Comment by mrsteele** [comment]
Hey @lmmarsano And I appreciate this PR.

According to the docs, they recommend you submit this to the @types org for npm.

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

If you disagree, let me know (I'm not really a typed-style person...)

**Comment by lmmarsano** [comment]
That document says the preferred approach is

> 1. bundling with your npm package

when written in TypeScript, as done in this pull-request.
I chose this approach because

1. Better user experience (no hunting down an additional package)
2. Easier to author (your code required basically no changes other than file name extensions, and the declaration files are automatically generated).
3. Opportunity to update dependencies that were raising warnings

Since you don't do TypeScript, I can add npm script to always build before publish to ease it a bit.
Let me know if you're persuaded.
There are always options, so no pressure.

**Comment by lmmarsano** [comment]
That document says the preferred approach is

> 1. bundling with your npm package

when written in TypeScript, as done in this pull-request.
I chose this approach because

1. Better user experience (no hunting down an additional package)
2. Easier to author (your code required basically no changes other than file name extensions, and the declaration files are automatically generated).
3. Opportunity to update dependencies that were raising warnings

Since you don't do TypeScript, I can add npm script to always build before publish to ease it a bit.
Let me know if you're persuaded.
There are always options, so no pressure.

**Comment by mrsteele** [comment]
Continue reading to the next paragraph. It says explicitly the following:

“If your package is not written in TypeScript then the second is the preferred approach.”

**Comment by lmmarsano** [comment]
Right, this pull-request writes it in TypeScript, in keeping with the 1st
approach.
The reasons before (primarily better user experience, but also because it
was plain easier to do it this way for your package) explain why this
pull-request takes that approach.
I can understand if you're strongly opposed, though.

**Comment by LubomirGeorgiev** [comment]
It can also be used this way with TypeScript #14

**Comment by LubomirGeorgiev** [comment]
In v1.1.1 and above you can use it with TypeScript [like this](https://github.com/mrsteele/dotenv-defaults#typescript) and Type Definitions are not needed, really.

@mrsteele I think this issue can be closed for good.

**Comment by peterblazejewicz** [comment]
fyi: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46273

**Comment by mrsteele** [comment]
Love it @peterblazejewicz !

**Pull request closed without merging**
