### PR TITLE
Bump dotenv@14.0.0

### PR DESCRIPTION
**Pull request by motdotla**
Hi 👋 @mrsteele. Thank you for dotenv-defaults 💛. This bumps it up to the latest dotenv@14.0.0.

### CODE REVIEW

**Comment by mrsteele** [comment]
Hey @motdotla . Thank you for `dotenv`! I'll flag this for breaking change and merge it in.

**Comment by motdotla** [comment]
Hey @mrsteele. I'd like to discuss two things with you if you would be interested in learning more:

1. Dotenv Foundation
2. Dotenv Vault

**Comment by mrsteele** [comment]
I’d like to hear from you about said things 😉 

you got me on GitHub (and Twitter as I saw), just tell me how.

**Comment by motdotla** [comment]
well the thing is, I don't know how to get in touch with you 😆. Twitter will not let me DM you.

**Pull request merged**
