### PR TITLE
Update dotenv

### PR DESCRIPTION
**Pull request by NachtRitter**
This pull request updates version of `dotenv` package.
According to `dotenv` [changelog](https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md) there are couple of breaking changes:
- dropping support of node v6
- removing `load` alias for `config`

### CODE REVIEW

**Comment by NachtRitter** [comment]
Hey @mrsteele !
Could you please merge and release new version?
As far as new versions of `dotenv` has breaking changes, so I guess `dotenv-defaults` should be released as 2.0.0 according to semver. 
Many thanks!

P.S. Also this pull requests https://github.com/mrsteele/dotenv-defaults/pull/7 and https://github.com/mrsteele/dotenv-defaults/pull/11 could be closed.

**Comment by mrsteele** [comment]
@NachtRitter this deletes a property, also I think it would mess up backwards compatibility.

**Comment by NachtRitter** [comment]
@mrsteele yeap, that's why I propose to release it as 2.0.0 that indicates that release has breaking changes.
if you worry about such things, I may add CHANGELOG.md and/or UPGRADE.md
What do you thing?

**Comment by mrsteele** [comment]
So we use [semantic-release](https://github.com/semantic-release/semantic-release) and if I merge this right now, a lot of packages would instantly break who depend on this.

You need to flag it as `BREAKING CHANGE: ____` before it can even be considered.

**Comment by nwalters512** [comment]
@NachtRitter do you have any plans to see this through? Otherwise I'm happy to open a new PR.

**Comment by mrsteele** [comment]
@nwalters512 Yeah perhaps a new PR would be fine.

Taken from https://www.conventionalcommits.org/en/v1.0.0-beta.2/
> BREAKING CHANGE: a commit that has the text BREAKING CHANGE: at the beginning of its optional body or footer section introduces a breaking API change (correlating with MAJOR in semantic versioning). A breaking change can be part of commits of any type. e.g., a fix:, feat: & chore: types would all be valid, in addition to any other type.

Example message:
```
fix: bumping dotenv
BREAKING CHANGE: This version may break in older versions of node.
```

**Comment by nwalters512** [comment]
@mrsteele I've opened #18, let me know if I got the commit messages right!

**Comment by mrsteele** [comment]
Closed in favor of #18.

**Pull request closed without merging**
