### PR TITLE
Add TypeScript and CLI support

### PR DESCRIPTION
**Pull request by LubomirGeorgiev**
This is a great module but it's a bit of a pain when you want to use it with TypeScript.

This PR adds TypeScript support.

### CODE REVIEW

**Review by mrsteele — CHANGES_REQUESTED** [review]
I like this, BUT I think I would like to stick with what the original dotenv library did: https://github.com/motdotla/dotenv/blob/master/config.js

Can we change `init` go be called `config`?

**Comment by LubomirGeorgiev** [comment]
> I like this, BUT I think I would like to stick with what the original dotenv library did: https://github.com/motdotla/dotenv/blob/master/config.js
> 
> Can we change `init` go be called `config`?

Done

**Review by mrsteele — APPROVED** [review]

**Comment by LubomirGeorgiev** [comment]
I forgot to add `config.js` to NPM so #15 should also be merged in order for this to work.

**Pull request merged**
